# Generated by Django 3.2.2 on 2023-07-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='factory.district')),
                ('location', models.CharField(max_length=100)),
                ('lat', models.FloatField(max_length=100)),
                ('lon', models.FloatField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('raw_materials', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('date_built', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('condition', models.CharField(choices=[('Green', 'Green'), ('Brown', 'Brown')], max_length=100)),
                ('category', models.CharField(choices=[('Agric', 'Agric'), ('Tech', 'Tech')], max_length=100)),
            ],
            options={
                'ordering': ['-date_built'],
            },
        ),
    ]
