# Generated by Django 3.2.2 on 2023-08-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='condition',
            field=models.CharField(choices=[('Green', 'Green'), ('Brown', 'Brown'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='factory',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='factory.district'),
        ),
    ]
