# Generated by Django 3.2.2 on 2023-08-06 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_auto_20230806_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='factory.district'),
        ),
    ]
